### ISSUE TITLE
Borgmatic Backup

### ISSUE THREAD

**Issue by modem7** [michaeltoohig/michaeltoohig.github.io#1]
Heya @michaeltoohig, 

Apologies for reaching out to you via GitHub issues! I couldn't see any other contact info.

Thanks for mentioning my blog/wiki post on your [blog](https://michaeltoohig.com/blog/dockerized-borgmatic/). Fantastically written!

Just to expand a couple of things which you may not be aware of which may be useful, are the other environment variables that you can use. 

This is insanely useful when you want to change your folders/repos without mucking around with the config file(s). 

This is my current compose file snippet:

```yaml
  borgmatic:
    image: modem7/borgmatic-docker
    # image: modem7/borgmatic-docker:1.8.13-1.4.0
    # image: borgmatic:test
    # image: ghcr.io/borgmatic-collective/borgmatic
    container_name: Borgmatic
    environment:
      TZ: $TZ
      BORG_PASSPHRASE: $BORG_PASSPHRASE
      BORG_SOURCE_1: $BORG_SOURCE_1
      BORG_SOURCE_2: $BORG_SOURCE_2
      BORG_REPO: $BORG_REPO
      BORG_HEALTHCHECK_URL: $BORG_HEALTHCHECK_URL
      # EXTRA_PKGS: postgresql16-client rclone coreutils jq
      DOCKERCLI: true
      CRON: $BORG_CRON
      CRON_COMMAND: $BORG_CRON_COMMAND
      # EXTRA_CRON: |-
      #   @daily borgmatic check -v 1 2>&1 > tee /mnt/log/check-$(date +\%Y-\%m-\%dT\%H:\%M:\%S).log
      #   0 7 1 * * command2
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - $BORGHOMESOURCEDIR:/mnt/source/
      # - $CRONTAB:/mnt/source/Cron
      # - Pihole:/mnt/source/Pihole/Pihole
      # - Dnsmasq:/mnt/source/Pihole/Dnsmasq
      - $BORGSERVBACKUPDIR/Database:/mnt/borg-DBrepository
      - $BORGSERVBACKUPDIR/Docker:/mnt/borg-repository
      - $RAMDRIVEBACKUP/borg:/mnt/ramdrive
      - $USERDIR:/mnt/source/DockerApps/
      - $USERDIR/Borgmatic/borgmatic.d/:/etc/borgmatic.d/
      - $USERDIR/Borgmatic/.config/borg/:/root/.config/borg
      - $USERDIR/Borgmatic/.ssh/:/root/.ssh
      - $USERDIR/Borgmatic/.state/:/root/.local/state/borgmatic
      - $USERDIR/Borgmatic/.cache/borg/:/root/.cache/borg
      - $DOCKERDIR/HDA/.env:/mnt/docker/HDA/.env:ro
      - $DOCKERDIR/HDA/docker-compose.yml:/mnt/docker/HDA/docker-compose.yml:ro
      - $BORGSCRIPTS:/borgscripts:ro
      - /var/run/docker.sock:/var/run/docker.sock # So we can run scripts
      # - /mnt/downloads/script/:/custom-cont-init.d:ro
    networks:
      isonet:
      isolated:
    restart: always
```

You can see I have four variables that I use:

```yaml
BORG_SOURCE_1: $BORG_SOURCE_1
BORG_SOURCE_2: $BORG_SOURCE_2
BORG_REPO: $BORG_REPO
BORG_HEALTHCHECK_URL: $BORG_HEALTHCHECK_URL
```

In your borg config file, you can do the following:

```yaml
source_directories:
     - ${BORG_SOURCE_1}
     - ${BORG_SOURCE_2}
repositories:
     - path: ${BORG_REPO}
       label: Borgbase
one_file_system: true
exclude_caches: true

#storage:
#   Passphase is set in variable $BORG_PASSPHRASE
compression: lz4
archive_name_format: 'backup-{now}'

keep_hourly: 0
keep_daily: 7
keep_weekly: 4
keep_monthly: 12
keep_yearly: 1

checks:
  - name: repository
    frequency: 2 weeks

before_everything:
    - echo "Stopping containers."
    - exec /borgscripts/docker-stop.sh
after_everything:
    - echo "Starting containers."
    - exec /borgscripts/docker-start.sh
    - echo "Backup created."
on_error:
    - echo "Error while creating a backup."
    - exec /borgscripts/docker-start.sh
    # https://torsion.org/borgmatic/docs/how-to/backup-your-databases/

healthchecks:
    ping_url: ${BORG_HEALTHCHECK_URL}
```

The benefit to this, is that when you change the variables and compose up your project, it will restart the container at the same time, saving you a bit of admin, and also allowing you to set things programmatically as well, especially if you have multiple servers that share the same config layout, but have different variables.

The other potential option you have, is instead of having multiple repos and configurations in a single config file, is to utilise [multiple configs](https://torsion.org/borgmatic/docs/how-to/make-per-application-backups/) which may make it easier to manage, especially from an environment variable PoV, or if you have different retention and/or check policies per repo etc.

You can also use [Docker secrets](https://torsion.org/borgmatic/docs/how-to/provide-your-passwords/#container-secrets) or [file based secrets](https://torsion.org/borgmatic/docs/how-to/provide-your-passwords/#file-based-credentials) if you wish. But that's definitely not the easiest path for most people.

I'm also using docker-in-docker (DinD) which allows me to perform functions on my Docker stack, which is quite useful with shutting down containers before backing up (e.g. databases or log files).

Hope that helps!
